# Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,10,23,19])

arr

array([ 4,  2,  3,  4,  5,  6, 10, 23, 19])

In [4]:
arr = arr.reshape(3,3)

arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 23, 19]])

In [5]:
arr2 = arr * 10 + 3
arr2

array([[ 13,  23,  33],
       [ 43,  53,  63],
       [103, 233, 193]])

# x[start:stop:step]

In [6]:
arr2[0:3,2]

array([ 33,  63, 193])

In [7]:
arr2[2,0:3]

array([103, 233, 193])

In [8]:
arr2[0:3:2]

array([[ 13,  23,  33],
       [103, 233, 193]])

In [9]:
arr2[0:3,0]

array([ 13,  43, 103])

In [10]:
arr2[0:2,1]

array([23, 53])

In [11]:
arr1 = np.arange(11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [12]:
arr2 = np.arange(5,11)
print(arr2)

[ 5  6  7  8  9 10]


In [13]:
arr3 = np.arange(5,11,2)
print(arr3)

[5 7 9]


In [14]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
np.linspace(1,1000,10)

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr4 = np.random.rand(5)

print(arr4)

[0.68400565 0.30275512 0.68862329 0.0861489  0.71515772]


In [23]:
import random

random.seed(5)
print(random.random())

0.6229016948897019


In [112]:
arr5 = np.random.rand(5,3).round(2)

print(arr5)

[[0.04 0.92 0.89]
 [0.17 0.35 0.65]
 [0.93 0.57 0.56]
 [0.36 0.22 0.8 ]
 [0.22 0.91 0.65]]


In [25]:
arr6 = np.random.randint(1,100)

arr6

79

In [27]:
arr7 = np.random.randint(1,100,10)

arr7

array([24, 64, 41, 19, 85, 33, 45, 73, 82, 95])

In [28]:
arr7.max()

95

In [29]:
arr7.argmax()

9

In [26]:
arr7.min()

17

In [27]:
arr7.argmin()

1

# Pandas

In [52]:
import pandas as pd

In [53]:
arr = np.array([1,7,44,9,3,5,6])
pd.Series(arr)

0     1
1     7
2    44
3     9
4     3
5     5
6     6
dtype: int32

In [54]:
ser1 = pd.Series([1,2,3,4],index = ['Azerbaijan', 'Turkey','Pakistan', 'Japan'])

print(ser1)

Azerbaijan    1
Turkey        2
Pakistan      3
Japan         4
dtype: int64


In [55]:
print(ser1['Turkey'])

2


### DataFrame

In [56]:
from numpy.random import randn

df = pd.DataFrame(randn(5,4),index=['A', 'B', 'C', 'D', 'E'],columns=['W', 'X', 'Y', 'Z'])
df

W         X         Y         Z
A -0.567630 -1.085150  1.016823  0.272164
B -2.335549  0.039612  1.674905 -0.303578
C  0.825835 -0.675309  1.825385 -1.046990
D -1.357240 -0.101891 -1.485399 -1.398306
E -0.897500 -0.204488  0.063070  1.516512

In [57]:
dfd = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
dfd

W         X         Y         Z
A -1.217162 -0.921702 -0.127683  0.894536
B -0.093937 -0.218549 -1.013908 -0.879388
C -0.939116 -0.703592  1.159089 -0.165474
D -0.321304  0.228381  0.343416 -0.811887
E -0.333743  1.909363  0.845784 -1.691171

In [58]:
df['W']

A   -0.567630
B   -2.335549
C    0.825835
D   -1.357240
E   -0.897500
Name: W, dtype: float64

In [59]:
df[['X','Z']]

X         Z
A -1.085150  0.272164
B  0.039612 -0.303578
C -0.675309 -1.046990
D -0.101891 -1.398306
E -0.204488  1.516512

In [60]:
df['new'] = df['W'] + df['Y']

df

W         X         Y         Z       new
A -0.567630 -1.085150  1.016823  0.272164  0.449192
B -2.335549  0.039612  1.674905 -0.303578 -0.660644
C  0.825835 -0.675309  1.825385 -1.046990  2.651219
D -1.357240 -0.101891 -1.485399 -1.398306 -2.842639
E -0.897500 -0.204488  0.063070  1.516512 -0.834430

In [61]:
a = df.drop('new', axis=1)


In [62]:
print(a, '\n')

          W         X         Y         Z
A -0.567630 -1.085150  1.016823  0.272164
B -2.335549  0.039612  1.674905 -0.303578
C  0.825835 -0.675309  1.825385 -1.046990
D -1.357240 -0.101891 -1.485399 -1.398306
E -0.897500 -0.204488  0.063070  1.516512 



In [42]:
df.drop('new', axis=1, inplace = True)

df
# or    x = df.drop('new',axis=1)

W         X         Y         Z
A -0.259123 -0.555817  0.139695 -0.965021
B -2.731945  0.272875 -0.390357 -0.834703
C  0.742445 -1.006459 -0.478281 -0.252934
D -0.170992  1.521765 -1.420937  1.357374
E -1.280781 -0.166095 -0.621092 -0.570407

In [43]:
df.drop('E', axis = 0, inplace = True)
df

W         X         Y         Z
A -0.259123 -0.555817  0.139695 -0.965021
B -2.731945  0.272875 -0.390357 -0.834703
C  0.742445 -1.006459 -0.478281 -0.252934
D -0.170992  1.521765 -1.420937  1.357374

In [44]:
# Sətirin select olunmasi: 
df.loc['A']

W   -0.259123
X   -0.555817
Y    0.139695
Z   -0.965021
Name: A, dtype: float64

In [45]:
# index - e gore select olunmasi : 

df.iloc[0]

W   -0.259123
X   -0.555817
Y    0.139695
Z   -0.965021
Name: A, dtype: float64

In [43]:
df.loc['B','Y']

-0.5339271118785731

In [44]:
df.loc[['A','B'],['W','Y']]

W         Y
A  0.888974 -0.252445
B -1.222364 -0.533927

### Serti ifadeler

In [45]:
df

W         X         Y         Z
A  0.888974 -0.212128 -0.252445  1.974720
B -1.222364 -0.791491 -0.533927 -0.873381
C -0.269186 -0.469954 -1.352672  0.176760
D -0.393443  0.030380 -0.413036 -0.319130

In [46]:
df > 0

W      X      Y      Z
A   True  False  False   True
B  False  False  False  False
C  False  False  False   True
D  False   True  False  False

In [47]:
df[df>0]

W        X   Y        Z
A  0.888974      NaN NaN  1.97472
B       NaN      NaN NaN      NaN
C       NaN      NaN NaN  0.17676
D       NaN  0.03038 NaN      NaN

In [48]:
df[df['W']>0]

W         X         Y        Z
A  0.888974 -0.212128 -0.252445  1.97472

In [49]:
df[(df['W']>0) & (df['Z'] > 0)]

W         X         Y        Z
A  0.888974 -0.212128 -0.252445  1.97472

#### Advanced indexing

In [50]:
df

W         X         Y         Z
A  0.888974 -0.212128 -0.252445  1.974720
B -1.222364 -0.791491 -0.533927 -0.873381
C -0.269186 -0.469954 -1.352672  0.176760
D -0.393443  0.030380 -0.413036 -0.319130

In [51]:
df.reset_index()

index         W         X         Y         Z
0     A  0.888974 -0.212128 -0.252445  1.974720
1     B -1.222364 -0.791491 -0.533927 -0.873381
2     C -0.269186 -0.469954 -1.352672  0.176760
3     D -0.393443  0.030380 -0.413036 -0.319130

In [52]:
df['States'] = 'CA NY WY OR'.split()
df

W         X         Y         Z States
A  0.888974 -0.212128 -0.252445  1.974720     CA
B -1.222364 -0.791491 -0.533927 -0.873381     NY
C -0.269186 -0.469954 -1.352672  0.176760     WY
D -0.393443  0.030380 -0.413036 -0.319130     OR

In [53]:
df.set_index('States', inplace = True)
df

W         X         Y         Z
States                                        
CA      0.888974 -0.212128 -0.252445  1.974720
NY     -1.222364 -0.791491 -0.533927 -0.873381
WY     -0.269186 -0.469954 -1.352672  0.176760
OR     -0.393443  0.030380 -0.413036 -0.319130

### Missing Data-lar








In [55]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [56]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [57]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [58]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [59]:
df.fillna(value='new value')

A          B  C
0          1          5  1
1          2  new value  2
2  new value  new value  3

In [60]:
df['A'].fillna(value=df['A'].mean(), inplace = True)

In [61]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

#### group by

In [62]:
data = {'Company':['Google','Google','Microsoft','Microsoft','Facebook','Facebook'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

df = pd.DataFrame(data)

df

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   Facebook     Carl    243
5   Facebook    Sarah    350

In [63]:
by_company = df.groupby("Company")

by_company.mean()

Sales
Company         
Facebook   296.5
Google     160.0
Microsoft  232.0

In [64]:
by_company.std()

Sales
Company              
Facebook    75.660426
Google      56.568542
Microsoft  152.735065

In [65]:
by_company.min()

Person  Sales
Company                  
Facebook      Carl    243
Google     Charlie    120
Microsoft      Amy    124

In [66]:
by_company.max()

Person  Sales
Company                  
Facebook     Sarah    350
Google         Sam    200
Microsoft  Vanessa    340

In [67]:
by_company.count()

Person  Sales
Company                 
Facebook        2      2
Google          2      2
Microsoft       2      2

In [68]:
by_company.describe()

Sales                                                        
          count   mean         std    min     25%    50%     75%    max
Company                                                                
Facebook    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
Google      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
Microsoft   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [69]:
by_company.describe().transpose()

Company        Facebook      Google   Microsoft
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [70]:
by_company.describe().transpose()['Google']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: Google, dtype: float64

#### operations

In [129]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4,5],'col2':[444,555,666,444,666],'col3':['abc','def','ghi','xyz','kds']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz
4     5   666  kds

In [131]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [73]:
df['col2'].nunique()

3

In [74]:
df['col2'].value_counts()

444    2
666    2
555    1
Name: col2, dtype: int64

In [75]:
df['col1'].sum()

15

In [76]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [77]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [78]:
df.sort_values(by='col3') #inplace=False by default

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
4     5   666  kds
3     4   444  xyz

#### Pivot table

In [79]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [80]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## Real-case Examples

In [81]:
df = pd.read_csv('bank.csv')
df

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [82]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [83]:
df.tail()

age          job  marital  education default  balance housing loan  \
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no

In [84]:
df.shape

(11162, 17)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [86]:
df.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [87]:
df.mean()

age           41.231948
balance     1528.538524
day           15.658036
duration     371.993818
campaign       2.508421
pdays         51.330407
previous       0.832557
dtype: float64

In [88]:
df.corr()

age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.112300 -0.000762  0.000189 -0.005278  0.002774  0.020169
balance   0.112300  1.000000  0.010467  0.022436 -0.013894  0.017411  0.030805
day      -0.000762  0.010467  1.000000 -0.018511  0.137007 -0.077232 -0.058981
duration  0.000189  0.022436 -0.018511  1.000000 -0.041557 -0.027392 -0.026716
campaign -0.005278 -0.013894  0.137007 -0.041557  1.000000 -0.102726 -0.049699
pdays     0.002774  0.017411 -0.077232 -0.027392 -0.102726  1.000000  0.507272
previous  0.020169  0.030805 -0.058981 -0.026716 -0.049699  0.507272  1.000000

In [89]:
df.count()

age          11162
job          11162
marital      11162
education    11162
default      11162
balance      11162
housing      11162
loan         11162
contact      11162
day          11162
month        11162
duration     11162
campaign     11162
pdays        11162
previous     11162
poutcome     11162
deposit      11162
dtype: int64

In [90]:
df.max()

age               95
job          unknown
marital       single
education    unknown
default          yes
balance        81204
housing          yes
loan             yes
contact      unknown
day               31
month            sep
duration        3881
campaign          63
pdays            854
previous          58
poutcome     unknown
deposit          yes
dtype: object

In [91]:
df.min()

age                18
job            admin.
marital      divorced
education     primary
default            no
balance         -6847
housing            no
loan               no
contact      cellular
day                 1
month             apr
duration            2
campaign            1
pdays              -1
previous            0
poutcome      failure
deposit            no
dtype: object

In [92]:
df.median()

age          39.0
balance     550.0
day          15.0
duration    255.0
campaign      2.0
pdays        -1.0
previous      0.0
dtype: float64

In [93]:
df.std()

age           11.913369
balance     3225.413326
day            8.420740
duration     347.128386
campaign       2.722077
pdays        108.758282
previous       2.292007
dtype: float64

In [94]:
df['age'].head()

0    59
1    56
2    41
3    55
4    54
Name: age, dtype: int64

In [95]:
df[df['age']>65]

age         job   marital  education default  balance housing loan  \
1142    68     retired  divorced    primary      no      250      no   no   
1162    75     retired  divorced    primary      no     3881     yes   no   
1168    69     retired   married    primary      no      324      no   no   
1180    69  management   married   tertiary      no      840      no   no   
1199    66  technician   married  secondary      no        0      no   no   
...    ...         ...       ...        ...     ...      ...     ...  ...   
10651   67  management   married  secondary      no     1287      no   no   
10721   73     retired   married    primary      no     1388      no   no   
10731   74     retired   married  secondary      no     3771      no   no   
10798   67  technician   married  secondary      no        0      no   no   
10843   86     retired  divorced    unknown      no      157      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  \
1142    cellular    3   feb       360         1     -1         0  unknown   
1162    cellular    4   feb       136         3     -1         0  unknown   
1168    cellular    4   feb       136         4     -1         0  unknown   
1180   telephone    5   feb       128         3     -1         0  unknown   
1199    cellular    6   feb       751         1     -1         0  unknown   
...          ...  ...   ...       ...       ...    ...       ...      ...   
10651   cellular    2   feb       511         1     -1         0  unknown   
10721   cellular   20   jul       146         3    190         3  success   
10731  telephone   16   apr       159         1     -1         0  unknown   
10798   cellular   13   aug      1152         2    188         1  success   
10843  telephone    7   sep       147         1     -1         0  unknown   

      deposit  
1142      yes  
1162      yes  
1168      yes  
1180      yes  
1199      yes  
...       ...  
10651      no  
10721      no  
10731      no  
10798      no  
10843      no  

[398 rows x 17 columns]

In [96]:
df.sort_values('age')

age      job   marital education default  balance housing loan  \
2935   18  student    single   primary      no      608      no   no   
3174   18  student    single   unknown      no      108      no   no   
4219   18  student    single   unknown      no        3      no   no   
2498   18  student    single   primary      no      608      no   no   
3494   18  student    single   unknown      no      348      no   no   
...   ...      ...       ...       ...     ...      ...     ...  ...   
2802   92  retired   married   unknown      no      775      no   no   
3098   92  retired   married   unknown      no      775      no   no   
3822   93  retired   married   unknown      no      775      no   no   
3756   93  retired   married   unknown      no      775      no   no   
1582   95  retired  divorced   primary      no     2282      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
2935   cellular   13   nov       210         1     93         1  success   
3174   cellular    9   feb        92         1    183         1  success   
4219   cellular   25   aug       130         2     -1         0  unknown   
2498   cellular   12   aug       267         1     -1         0  unknown   
3494   cellular    5   may       443         4     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
2802   cellular   22   oct       313         3     -1         0  unknown   
3098   cellular   26   jan       164         4     96         3  success   
3822   cellular    4   aug       476         2     13         9  success   
3756   cellular   22   jul       860         2    177         7  success   
1582  telephone   21   apr       207        17     -1         0  unknown   

     deposit  
2935     yes  
3174     yes  
4219     yes  
2498     yes  
3494     yes  
...      ...  
2802     yes  
3098     yes  
3822     yes  
3756     yes  
1582     yes  

[11162 rows x 17 columns]

In [97]:
df.groupby("age").mean()

balance        day     duration   campaign      pdays  previous
age                                                                     
18    237.000000  13.250000   202.625000   1.625000  33.750000  0.250000
19    283.153846  13.076923   228.846154   1.923077  70.692308  0.615385
20   1013.200000  16.150000   255.050000   2.000000  51.000000  1.300000
21   1064.200000  13.900000   294.333333   1.966667  45.100000  0.833333
22    844.979167  15.375000   260.125000   1.645833  59.770833  1.020833
..           ...        ...          ...        ...        ...       ...
89    553.000000  19.000000  2027.000000   5.000000  -1.000000  0.000000
90    356.500000   8.000000   354.500000   2.000000  -1.000000  0.000000
92    775.000000  24.000000   238.500000   3.500000  47.500000  1.500000
93    775.000000  13.000000   668.000000   2.000000  95.000000  8.000000
95   2282.000000  21.000000   207.000000  17.000000  -1.000000  0.000000

[76 rows x 6 columns]

In [98]:
df.groupby(["age","balance"]).mean()

day    duration  campaign      pdays  previous
age balance                                                 
18  3        25.0  130.000000       2.0  -1.000000  0.000000
    5        24.0  143.000000       2.0  -1.000000  0.000000
    108       9.0  142.666667       1.0  60.333333  0.333333
    348       5.0  443.000000       4.0  -1.000000  0.000000
    608      12.5  238.500000       1.0  46.000000  0.500000
...           ...         ...       ...        ...       ...
90  1        13.0  152.000000       3.0  -1.000000  0.000000
    712       3.0  557.000000       1.0  -1.000000  0.000000
92  775      24.0  238.500000       3.5  47.500000  1.500000
93  775      13.0  668.000000       2.0  95.000000  8.000000
95  2282     21.0  207.000000      17.0  -1.000000  0.000000

[9219 rows x 5 columns]

In [99]:
pd.isnull(df)

age    job  marital  education  default  balance  housing   loan  \
0      False  False    False      False    False    False    False  False   
1      False  False    False      False    False    False    False  False   
2      False  False    False      False    False    False    False  False   
3      False  False    False      False    False    False    False  False   
4      False  False    False      False    False    False    False  False   
...      ...    ...      ...        ...      ...      ...      ...    ...   
11157  False  False    False      False    False    False    False  False   
11158  False  False    False      False    False    False    False  False   
11159  False  False    False      False    False    False    False  False   
11160  False  False    False      False    False    False    False  False   
11161  False  False    False      False    False    False    False  False   

       contact    day  month  duration  campaign  pdays  previous  poutcome  \
0        False  False  False     False     False  False     False     False   
1        False  False  False     False     False  False     False     False   
2        False  False  False     False     False  False     False     False   
3        False  False  False     False     False  False     False     False   
4        False  False  False     False     False  False     False     False   
...        ...    ...    ...       ...       ...    ...       ...       ...   
11157    False  False  False     False     False  False     False     False   
11158    False  False  False     False     False  False     False     False   
11159    False  False  False     False     False  False     False     False   
11160    False  False  False     False     False  False     False     False   
11161    False  False  False     False     False  False     False     False   

       deposit  
0        False  
1        False  
2        False  
3        False  
4        False  
...        ...  
11157    False  
11158    False  
11159    False  
11160    False  
11161    False  

[11162 rows x 17 columns]

In [100]:
pd.isnull(df).sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [101]:
df.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000